version: "3.8"

services:
  nextjs:
    container_name: nextjs-app-example-loginPage-demo
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3099:3000"
    restart: always
    env_file:
      - .env
    volumes:
      - ./:/app
      - /app/node_modules
